# Uncomment the next line to define a global platform for your project
# platform :ios, '11.0'

target 'Vitamin' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'Alamofire'
  pod 'SDWebImage'
  pod 'SwiftLint'

  # Pods for Vitamin

  target 'VitaminTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'VitaminUITests' do
    # Pods for testing
  end

end
